### ISSUE TITLE
Possibility to operate launcher without needing intents

### ISSUE THREAD

**Issue by saschaknapp** [fiskaltrust/middleware-launcher-android#69]
## Background

We have a new customer who is interested in implementing the middleware on android. Their software can't use the android intent functions. Using chrome isn't an option either. Normally in these kind of architectures byodc is the best solution, but the cutstomer wants to use a hardware TSE in the german market.

## Feature

It would be great if there was an option to use the android launcher without needing intents. The dealer/operator would then be responsible for the running middleware service on the android device.

**Comment by volllly** [comment]
Since android is quite harsh (and getting harsher) when it comes to keeping services running in the background the PosOperator would have to manually restart the launcher quite often.

We don't think its feasible to operate in this way as its error prone and not very automatic.

**Comment by fox-buddy** [comment]
Hello,

i am the refered Customer.
I maybe would develop a Plugin for my App that is able to work with intents.

Is there a documentation, what specific INTENTS are needed?

**Comment by volllly** [comment]
Hey,

in the [middleware-demo-android](https://github.com/fiskaltrust/middleware-demo-android) repo we have C# and Java sample code that shows how to interact with the android-launcher as well as documentation on how to operate the android-launcher like [what intents need to be sent](https://github.com/fiskaltrust/middleware-demo-android?tab=readme-ov-file#minimal-sample).
